name: Codex → v10.1 (auto-merge y build)

on:
  push:
    branches:
      - "codex/**"   # se activa cuando Codex empuja a cualquier rama codex/...

permissions:
  contents: write     # permiso para empujar a v10.1

jobs:
  merge_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (historia completa)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            extras;google;m2repository
            extras;android;m2repository

      - name: Detectar rama Codex
        id: vars
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Configurar git para push
        run: |
          git config user.name  "codex-bot"
          git config user.email "codex-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      - name: Preparar merge en v10.1 (preferir cambios de Codex)
        run: |
          git fetch origin v10.1
          git checkout v10.1
          git merge -X theirs "${{ steps.vars.outputs.BRANCH }}" --no-commit --no-ff || true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Compilar
        run: ./gradlew --no-daemon :app:assembleDebug

      - name: Commit y push si hubo merge
        run: |
          if [ -d .git/MERGE_HEAD ]; then
            git commit -m "Auto-merge Codex '${{ steps.vars.outputs.BRANCH }}' → v10.1 [skip ci]"
          fi
          git push origin v10.1

      - name: Borrar rama remota codex
        run: git push origin --delete "${{ steps.vars.outputs.BRANCH }}" || true

